// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADRl9kDcJ5vsUepgRFZ0vg-JFZg8Qzjms',
    appId: '1:333636924892:web:9ca592ab44097e5af74b19',
    messagingSenderId: '333636924892',
    projectId: 'chatapp-82522',
    authDomain: 'chatapp-82522.firebaseapp.com',
    storageBucket: 'chatapp-82522.appspot.com',
    measurementId: 'G-4GFSBSSQ08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoL94uDtgHHV3ZKib9a2a2-Mrx-mSr1tI',
    appId: '1:333636924892:android:959561b0346120faf74b19',
    messagingSenderId: '333636924892',
    projectId: 'chatapp-82522',
    storageBucket: 'chatapp-82522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSXov_eiqufJZyix1eq5CUM79tWZcBdo',
    appId: '1:333636924892:ios:d2503f53546d6ad1f74b19',
    messagingSenderId: '333636924892',
    projectId: 'chatapp-82522',
    storageBucket: 'chatapp-82522.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSXov_eiqufJZyix1eq5CUM79tWZcBdo',
    appId: '1:333636924892:ios:d2503f53546d6ad1f74b19',
    messagingSenderId: '333636924892',
    projectId: 'chatapp-82522',
    storageBucket: 'chatapp-82522.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADRl9kDcJ5vsUepgRFZ0vg-JFZg8Qzjms',
    appId: '1:333636924892:web:6841c3ba869e4641f74b19',
    messagingSenderId: '333636924892',
    projectId: 'chatapp-82522',
    authDomain: 'chatapp-82522.firebaseapp.com',
    storageBucket: 'chatapp-82522.appspot.com',
    measurementId: 'G-C8YKHCLNWD',
  );
}
